# Dockerfile for using pandas
#

FROM python:3.9.14

RUN pip3 install numpy pandas

# ENTRYPOINT [ "/usr/local/bin/blast2gff" ]
# ENTRYPOINT [ "/usr/local/bin/FastaToTbl" ]
# ENTRYPOINT [ "/usr/local/bin/geneid" ]
# ENTRYPOINT [ "/usr/local/bin/sgp_getHSPSR.pl" ]
